### ISSUE TITLE
Problem when the option by default Q&A in each post is On

### ISSUE THREAD

**Issue by celarain** [psychobunny/nodebb-plugin-question-and-answer#12] opened 2015-10-26 21:09 UTC
Hi there, I am having some problems when the Q&A is by dafault, if I press the select and then choose the default option it changes to Q&A anyway and sometimes adds 2 unsolved marks. Any way to solve this? 

![The error](http://i.imgur.com/gKa3ynk.png)
Thanks in advance

**Comment by celarain** [comment] 2015-11-10 08:30
No one can answer me? I am creating a programmin forum and its pretty important to be by default Q&A but still enable to send a normal post.

By the way, here added another if to look if its a question, because if before was a question and after was normal post, still had the mark of solved or unsolved.

`````
	function addLabel() {
		require(['components'], function(components) {
			if (parseInt(ajaxify.data.isQuestion, 10)) {
				if (parseInt(ajaxify.data.isSolved, 10) === 0) {
					components.get('post/header').prepend('<span class="unanswered"><i class="fa fa-question-circle"></i> Sin resolver</span>');
				} else if (parseInt(ajaxify.data.isSolved, 10) === 1) {
					components.get('post/header').prepend('<span class="answered"><i class="fa fa-question-circle"></i> Resuelta</span>');
				}
			}
		});
	}
``````

**Comment by julianlam** [comment] 2015-11-16 15:45
Looks to be reproducible, will address this shortly, thanks.

**Comment by celarain** [comment] 2015-11-17 13:26
Thanks in advance :D

**Comment by celarain** [comment] 2015-11-19 08:24
Hi again! You did the second comment fix but any answer for the first question?

If Q&A its marked to be by default, and then I choose to be a normal post, it still mark it as a Q&A.

**Comment by julianlam** [comment] 2015-11-19 13:15
That's the same issue, it should be fixed.

**Comment by celarain** [comment] 2015-11-19 13:35
Its happening the same, dont know if I explained wrong, hope this make you understand.

[Imgur](http://i.imgur.com/j6mo4La.jpg)

**Comment by julianlam** [comment] 2015-11-19 15:51
I don't believe the changes have been merged and published yet. Are you running latest git clone?

**Comment by celarain** [comment] 2015-11-19 16:14
I updated manually to try the changes, but not working. The error comes only when we are using this: 

`if (config['question-and-answer'].makeDefault === 'on') {`

**Closed** 2015-12-17 17:26 UTC

**Comment by ollipuu** [comment] 2016-02-15 13:50
Sorry for digging up this old issue, but I don't think this was completely fixed. In main.js#34 starts a condition to check, whether to set the QA as a default type.

```javascript
if (
        config['question-and-answer'].forceQuestions === 'on' ||
        (
                config['question-and-answer'].makeDefault === 'on' &&
                (config['question-and-answer'].defaultCid === "0" || parseInt(config['question-and-answer'].defaultCid, 10) === data.composerData.cid)
        )
) {
        $('.composer-submit').attr('data-action', 'post').html('<i class="fa fa-fw fa-question-circle"></i> Ask as Question</a>');
        $(window).off('action:composer.topics.post').one('action:composer.topics.post', function(ev, data) {
                callToggleQuestion(data.data.tid);
        });
}
```

If QA is the default, callToggleQuestion is called after the topic is created. Function callToggleQuestion calls toggleQuestionStatus in library.js, where topics.getTopicField triggers a callback with parameter isQuestion. Because the topic was just created, the value of isQuestion is null. The next comparison

```javascript
isQuestion = parseInt(isQuestion, 10) === 1;
```

sets the value of isQuestion to 0 and after that the code toggles the value to 1 so that when a new topic is created (if the default type is QA and no matter what the value of the dropdown is), the topic type will be a question.

Plugin version: 0.0.16
NodeBB version: 0.9.3 (cloned about a month ago)
Theme: Own theme, inherited from Vanilla.
